Custom easyocr
carscan/EasyOCR pull request #1
Opened 2023-01-19 18:01 UTC by siddhantcarscan

1. Added seperate paths for separate files. such as .yaml, .py, .pth
2. modified device = device. instead of gpu= bool.
3. Modified loading of model from single model using key. ['easyocr_weight']

2023-01-19 18:23 UTC, PushpakBhoge512 requested changes

2023-01-19 18:23 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +                 quantize=True, cudnn_benchmark=False, model_path=None ,yaml_path=None, model_arch=None):
we have added `model_path=None ,yaml_path=None, model_arch=None)` remove this parameters

2023-01-19 18:23 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +        sys.path.append(self.user_network_directory)
remove all of this directly set
```
self.model_path=model_path
self.yaml_path=yaml_path
self.model_arch=model_arch
```

2023-01-19 18:23 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +            detector_path = self.getDetectorPath(detect_network)
delete everythinhg related to detector where ever possible

2023-01-19 18:23 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +            # check recognition model file
delete this and raise exception with message "pretrained model loading not supported"

2023-01-19 18:23 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +            self.detector = self.initDetector(detector_path)
delete this

2023-01-19 18:23 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +        return detector_path
delete

2023-01-19 18:23 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +        self.detector = self.initDetector(detector_path)
delete

2023-01-19 18:23 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +        return horizontal_list_agg, free_list_agg
delete

2023-01-20 05:16 UTC, siddhantcarscan commented
Removed the unnecessary functions and params from Custom_Reader.

2023-01-20 05:53 UTC, PushpakBhoge512 requested changes

2023-01-20 05:53 UTC, PushpakBhoge512 commented on easyocr/easyocr.py
> +            print('user-defined model is not provided')
you have to raise error here not just print statement

2023-01-20 05:59 UTC, PushpakBhoge512 approved these changes

2023-01-20 06:00 UTC, merged